Feature/#3
4RG0S/2024-Spring-Homeless-BE pull request #4
Opened 2024-03-28 07:16 UTC by purplepig4657

This commit implements Comment entity that issued with #3.

# Need to be discussed

- [ ] Use JPA annotation when define relation mapping, e.g. OneToMany. Because I think this annotation makes affect between domains, So It violates DDD principle. It can be referenced with id, but this method increases complexity of project structure.
- [ ] Is There any annotation for improve SQL query?
- [ ] What method this domain entity should have?

# Need to be changed
- Change status field with ENUM class.

2024-03-28 13:33 UTC, jeomxon requested changes
간단하게 리뷰 남겨봤습니다!
역시 컴공 21 과탑은 다르네요 ㅎㅎ

2024-03-28 13:33 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +public class Comment extends BaseEntity {
`@NoArgsConstructor(access = AccessLevel.PROTECTED)`
`@EqualsAndHashCode(of = {"id"})`
요 두가지 어노테이션 있으면 좋을 것 같네요~

2024-03-28 13:33 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +public class Comment extends BaseEntity {
추가로 생성자를 막고 Builder를 쓰는 것에 대해 어떻게 생각하시는지 의견이 궁금합니다!

2024-03-28 13:33 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    @Column(name = "password", length = 80)
password값도 null을 허용하면 안될 것 같아요!

2024-03-28 13:37 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +public class Comment extends BaseEntity {
+ `comments`로 테이블 name을 설정한 이유가 있을까요?

2024-04-08 06:56 UTC, purplepig4657 commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +public class Comment extends BaseEntity {
> ++ `comments`로 테이블 name을 설정한 이유가 있을까요?

보동 어떻게 선언하나요 ??

2024-04-08 06:57 UTC, purplepig4657 commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    @Column(name = "password", length = 80)
comment에 password 가 있는 이유를 듣고 다시 생각해봐야 할 것 같습니다!

2024-04-08 07:02 UTC, purplepig4657 commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +public class Comment extends BaseEntity {
네 좋습니다! 반영하여 고쳐놓겠습니다 !

2024-04-08 07:15 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +public class Comment extends BaseEntity {
보통 어떻게 선언하는지는 잘 모르겠지만, 데이터베이스 예약어가 겹치는 경우 suffix로 's'를 붙이는 경우는 종종 보았던 것 같아요.
혹시나 그런 이유에서 붙이셨는지 궁금해서 물어봤습니다 :)

2024-04-08 13:22 UTC, jeomxon requested changes
간단하게 리뷰 남겼습니다 ㅎㅎ
궁금한 점이나 이해 안되는 부분은 언제든 연락주세요!

2024-04-08 13:22 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    private User user;
이 필드는 현재 Nullable하니 수정이 필요해보여요

2024-04-08 13:22 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    }
생성자의 위치는 컨벤션 상 맨 아래로 내리는 것이 좋습니다!

2024-04-08 13:22 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    }
빌더 패턴을 사용할 때는 생성자를 private으로 막아서 builder로만 생성하게 하는 것이 좋아보이네요

2024-04-08 13:22 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    @Column(name = "is_secret", nullable = false)
column에 name속성을 전부 지정해준 이유가 있을까요?

2024-04-09 01:09 UTC, purplepig4657 commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    }
private으로 만들고 Builder annotation을 붙인다면 public 생성자가 생성되나요 ??

2024-04-09 01:13 UTC, purplepig4657 commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    @Column(name = "is_secret", nullable = false)
JPA가 camlcase인 변수명을 자동으로 snakecase로 바꾸어 column name으로 사용하는 것 같은데, 저는 이런 명시적이지 않은 JPA 동작을 사용하는 것이 좋지 않다고 생각해서 name 속성을 명시적으로 표시하여 주었습니다.

변수 이름이 바뀔 때 column name도 같이 수정해주는 것은 그리 큰 오버헤드가 아닐 것 같습니다!

2024-04-09 01:16 UTC, purplepig4657 commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    private User user;
연관관계 매핑에도 Column annotation이 들어가는 게 맞나요?

2024-04-09 03:22 UTC, jeomxon requested changes
추가적으로 리뷰 남겼습니다!

2024-04-09 03:22 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    private User user;
`@JoinColumn`에서 지정할 수 있습니다~

2024-04-09 03:22 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    @Column(name = "is_secret", nullable = false)
좋은 생각입니다!
다만 말씀하신 것처럼 명시적이게 사용하려면 전부 명시해주는 것이 좋고, 그렇지 않다면 통일성있게 전부 하지 않는 것이 좋을 것 같아요.
이러한 이유로 user필드에도 column name을 넣어주시면 좋을 것 같습니다 ㅎㅎ

2024-04-09 03:22 UTC, jeomxon commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    }
Optional을 사용하는 의도는 좋은 것 같아요.
하지만 getter에서 또 다시 값을 꺼내오는 과정을 감수해야하긴 할 것 같네요..ㅎㅎ

2024-04-09 03:39 UTC, purplepig4657 commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    private User user;
아, 연관관계 매핑된 필드가 실제 DB table에 FK로 들어가는 방식이군요! 수정하겠습니다~

2024-04-09 03:40 UTC, purplepig4657 commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    }
네! Optional 이 오버헤드가 있다고는 하지만 nullable 처리를 강제하는 것이 더 좋아보입니다!

2024-04-09 03:44 UTC, purplepig4657 commented on src/main/java/kr/or/argos/domain/comment/entity/Comment.java
> +    }
https://github.com/4RG0S/2024-Spring-Homeless-BE/pull/6#discussion_r1556796456

2024-05-06 08:30 UTC, jeomxon approved these changes
👍🏻

2024-05-06 08:32 UTC, merged